openapi: 3.1.0
x-stoplight:
  id: 2t9kntrlyru6n
info:
  title: Инструкции
  description: Инструкции
  version: '1.0'
  contact:
    name: Абдурайимов Эльмар Нариманович
    email: elmar.abdurayimov@innostage-group.ru
servers:
  - url: 'http://127.0.0.1/api'
    description: test
  - url: 'http://10.70.41.64/api'
    description: dev
paths:
  /instructions:
    get:
      summary: indexInstructions
      responses:
        '200':
          description: Список инструкций
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: ../models/instruction.yaml
                  - $ref: ../models/components/pagination.yaml
                type: object
              examples:
                Example 1:
                  value:
                    data:
                      - id: 0
                        name: string
                        file: string
                    current_page: 0
                    last_page: 0
                    per_page: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-401.yaml
              examples: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-500.yaml
              examples: {}
      operationId: indexInstructions
      description: Получение всех инструкций
      parameters:
        - schema:
            type: integer
            minimum: 1
            maximum: 100
            example: 10
          in: query
          name: page
          description: Номер страницы
        - schema:
            type: integer
            example: 10
          in: query
          name: per_page
          description: Кол-во элементов на странице
        - schema:
            type: string
          in: query
          name: search
          description: Поисковая строка
        - schema:
            type: string
            example: id
          in: query
          name: sort_field
          description: Колонка для сортировки
        - schema:
            type: string
            example: asc
          in: query
          name: sort_order
          description: Направление сортировки
      security:
        - login: []
      tags:
        - inctructions
components:
  parameters: {}
  securitySchemes:
    login:
      type: http
      scheme: basic
      description: Базовая авторизация через битрикс. Нужна специальная доработка.
  requestBodies: {}
security:
  - login: []
tags:
  - name: inctructions
