openapi: 3.1.0
x-stoplight:
  id: 24m0dq43m1ilc
info:
  title: Организации
  description: Типы НПА
  version: '1.0'
  contact:
    name: Абдурайимов Эльмар Нариманович
    email: elmar.abdurayimov@innostage-group.ru
servers:
  - url: 'http://127.0.0.1/api'
    description: test
  - url: 'http://10.70.41.64/api'
    description: dev
paths:
  /organizations:
    get:
      summary: indexOrganizations
      tags:
        - organizations
      responses:
        '200':
          description: Список организаций
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: ../models/organization.yaml
              examples:
                Example 1:
                  value:
                    data:
                      - id: 1
                        name: Организация
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-401.yaml
              examples: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-500.yaml
              examples: {}
      operationId: indexOrganizations
      description: Получение всех организаций
      parameters: []
      security:
        - login: []
    parameters: []
components:
  parameters: {}
  securitySchemes:
    login:
      type: http
      scheme: basic
      description: Базовая авторизация через битрикс. Нужна специальная доработка.
  requestBodies: {}
security:
  - login: []
tags:
  - name: organizations
