openapi: 3.1.0
x-stoplight:
  id: hu7xo3asdzlks
info:
  title: Языки программирования
  description: API для языков программирования
  version: '1.0'
  contact:
    name: Абдурайимов Эльмар Нариманович
    email: elmar.abdurayimov@innostage-group.ru
servers:
  - url: 'http://127.0.0.1/api'
    description: test
  - url: 'http://10.70.41.64/api'
    description: dev
paths:
  /programming-languages:
    get:
      summary: indexProgrammingLanguages
      tags:
        - programming-languages
      responses:
        '200':
          description: Список языков программирования
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: ../models/programming-language.yaml
              examples:
                Example 1:
                  value:
                    data:
                      - id: 0
                        name: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-401.yaml
              examples: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-500.yaml
              examples: {}
      operationId: indexProgrammingLanguages
      description: Получение всех языков программирования
      parameters: []
      security:
        - login: []
    parameters: []
components:
  parameters: {}
  securitySchemes:
    login:
      type: http
      scheme: basic
      description: Базовая авторизация через битрикс. Нужна специальная доработка.
  requestBodies: {}
security:
  - login: []
tags:
  - name: programming-languages
