openapi: 3.1.0
x-stoplight:
  id: gmvm8266ay46d
tags:
  - name: regulations
    description: Нормативно правовые акты
info:
  title: Нормативно-правовые акты
  description: Нормативно-правовые акты
  version: '1.0'
  contact:
    name: Абдурайимов Эльмар Нариманович
    email: elmar.abdurayimov@innostage-group.ru
servers:
  - url: 'http://127.0.0.1/api'
    description: test
  - url: 'http://10.70.41.64/api'
    description: dev
paths:
  /regulations:
    get:
      summary: indexRegulations
      responses:
        '200':
          description: Список нормативно-правовых актов
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: ../models/regulation.yaml
                  - $ref: ../models/components/pagination.yaml
                type: object
                required:
                  - data
                  - current_page
                  - last_page
                  - per_page
              examples:
                Example 1:
                  value:
                    data:
                      - id: 0
                        regulation_type:
                          id: 0
                          name: string
                        organization:
                          id: 0
                          name: string
                        name: string
                        approval_date: ГГГГ-ММ-ДД
                        effective_date: ГГГГ-ММ-ДД
                        file: string
                        link: string
                    current_page: 0
                    last_page: 0
                    per_page: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-401.yaml
              examples: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-500.yaml
              examples: {}
      operationId: indexRegulations
      description: Получение всех нормативно-правовых актов
      parameters:
        - schema:
            type: integer
            minimum: 10
          in: query
          name: per_page
          minimum: 10
          description: Кол-во элементов на странице
        - schema:
            type: integer
            minimum: 1
          in: query
          name: page
          minimum: 1
          description: Номер страницы
        - schema:
            type: string
          in: query
          name: search
          description: Поисковая строка
        - schema:
            type: array
            uniqueItems: true
          in: query
          name: regulation_type_ids
          description: Типы НПА
          items:
            type: integer
        - schema:
            type: string
            format: date
            pattern: '^\d{4}-\d{2}-\d{2}$'
          in: query
          name: approval_date
          description: Дата утверждения
        - schema:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2}$'
            format: date
          in: query
          name: effective_date
          description: Дата введения в действие
        - schema:
            type: string
            default: name
            enum:
              - id
              - name
              - regulation_type_id
              - organization_id
              - approval_date
              - effective_date
          in: query
          name: sort_field
          description: Колонка для сортировки
        - schema:
            type: string
            default: asc
            enum:
              - asc
              - desc
          in: query
          name: sort_order
          description: Направление сортировки
      security:
        - login: []
      tags:
        - regulations
    parameters: []
    post:
      summary: storeRegulation
      operationId: storeRegulation
      responses:
        '200':
          description: Нормативно-правовой акт создан
          content:
            application/json:
              schema:
                $ref: ../models/regulation.yaml
              examples: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-401.yaml
              examples: {}
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-422.yaml
              examples: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-500.yaml
              examples: {}
      description: Создание нормативно-правового акта
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Название
                regulation_type_id:
                  type: integer
                  description: ID типа НПА
                approval_date:
                  type: string
                  description: Дата утверждения
                  example: ГГГГ-ММ-ДД
                effective_date:
                  type: string
                  description: Дата введения в действие
                  example: ГГГГ-ММ-ДД
                file:
                  type: string
                  description: Ссылка на файл
                link:
                  type: string
                  description: Ссылка
                organization_id:
                  type: integer
                  description: ID организации
              required:
                - name
                - regulation_type_id
                - approval_date
                - effective_date
            examples:
              Example 1:
                value:
                  name: string
                  regulation_type_id: 0
                  approval_date: ГГГГ-ММ-ДД
                  effective_date: ГГГГ-ММ-ДД
                  file: string
                  link: string
                  organization_id: 0
      tags:
        - regulations
  '/regulations/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID нормативно-правового акта
    patch:
      summary: updateRegulation
      operationId: updateRegulation
      responses:
        '200':
          description: Нормативно-правовой акт обновлен
          content:
            application/json:
              schema:
                $ref: ../models/regulation.yaml
              examples: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-401.yaml
              examples: {}
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-404.yaml
              examples: {}
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-422.yaml
              examples: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-500.yaml
              examples: {}
      description: Обновление нормативно-правового акта по Id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                organization_id:
                  type: integer
                  description: ID организации
              required:
                - organization_id
            examples:
              Example 1:
                value:
                  organization_id: 1
      tags:
        - regulations
    delete:
      summary: deleteRegulation
      operationId: deleteRegulation
      responses:
        '200':
          description: Нормативно-правовой акт удален
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    default: 200
                    example: 200
              examples: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-401.yaml
              examples: {}
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-404.yaml
              examples: {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-500.yaml
              examples: {}
      description: Удаление нормативно-правового акта по Id
      tags:
        - regulations
components:
  parameters: {}
  securitySchemes:
    login:
      type: http
      scheme: basic
      description: Базовая авторизация через битрикс. Нужна специальная доработка.
  requestBodies: {}
security:
  - login: []
