openapi: 3.1.0
info:
  title: Уязвимости найденные сканерами
  description: API для уязвимостей найденными сканерами
  version: '1.0'
  contact:
    name: Ульев Андрей Дмитриевич
    email: Andrey.Ulev@innostage-group.ru
servers:
  - url: 'http://127.0.0.1/api'
    description: test
  - url: 'http://10.70.41.64/api'
    description: dev
paths:
  '/scanning-vulnerabilities/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: Id уязвимости найденной сканерами
        example: 1
    get:
      operationId: showScanningVulnerability
      summary: showScanningVulnerability
      tags:
        - scanning-vulnerabilities
      description: Получение уязвимости найденной сканерами по Id
      responses:
        '200':
          description: Уязвимость найдена
          content:
            application/json:
              schema:
                $ref: ../models/scanning-vulnerability.yaml
              examples:
                Example 1:
                  value:
                    id: 1
                    rvision_id: 83582985-ad91-3616-bfc0-6ff6474a69a5
                    status: Устранена
                    type: Недостаточная проверка вводимых данных
                    vulnerability_id: 83582985-ad91-3616-bfc0-6ff6474a69a5
                    vulnerability_name: 'Уязвимость компонента PL/SQL системы управления базами данных Oracle Database Server, позволяющая нарушителю получить несанкционированный доступ к защищаемым данным или получить доступ на изменение, добавление или удаление защищаемых данных'
                    description: 'Уязвимость компонента PL/SQL системы управления базами данных Oracle Database Server связана с недостаточной проверкой входных данных. Эксплуатация уязвимости может позволить нарушителю, действующему удаленно, получить несанкционированный доступ к защищаемым данным или получить доступ на изменение, добавление или удаление защищаемых данных'
                    vulnerability_criticality: Вредоносная активность не обнаружена
                    discovered_at: '2021-01-22'
                    cvssv2: 5.8
                    cvssv3: 5.9
                    vector_v2: 'AV:N/AC:L/Au:M/C:P/I:P/A:P'
                    vector_v3: 'AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:L'
                    domain: oracle.com
                    host_ip: 95.101.178.195
                    port: 8080
                    host_name: 'https://www.oracle.com'
                    identification_src: 'https://www.oracle.com/security-alerts/cpuoct2023.html'
                    cve: 'https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2023-22071'
                    bdu_fstec: 'https://bdu.fstec.ru/vul/2023-06901'
                    references:
                      - source: NATIONAL VULNERABILITY DATABASE
                        url: 'https://nvd.nist.gov/vuln/detail/CVE-2023-22071'
                    software_vulnerabilities:
                      - cpe: Oracle Corp.
                        name: Database Server
                        path: /
                        version: от 19.3 до 19.19 включительно
                    dit_inc_result: Данные уточняются
                    removal_recommend: 'https://www.oracle.com/security-alerts/cpuoct2023.html'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-401.yaml
              examples: null
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-404.yaml
              examples: null
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-500.yaml
              examples: null
    patch:
      summary: updateScanningVulnerability
      operationId: updateScanningVulnerability
      tags:
        - scanning-vulnerabilities
      description: Обновление уязвимости найденной сканерами
      responses:
        '200':
          description: Заявка обновлена
          content:
            application/json:
              schema:
                $ref: ../models/scanning-vulnerability.yaml
              examples:
                Example 1:
                  value:
                    id: 1
                    rvision_id: 83582985-ad91-3616-bfc0-6ff6474a69a5
                    status: Открыта
                    type: Недостаточная проверка вводимых данных
                    vulnerability_id: 83582985-ad91-3616-bfc0-6ff6474a69a5
                    vulnerability_name: 'Уязвимость компонента PL/SQL системы управления базами данных Oracle Database Server, позволяющая нарушителю получить несанкционированный доступ к защищаемым данным или получить доступ на изменение, добавление или удаление защищаемых данных'
                    description: 'Уязвимость компонента PL/SQL системы управления базами данных Oracle Database Server связана с недостаточной проверкой входных данных. Эксплуатация уязвимости может позволить нарушителю, действующему удаленно, получить несанкционированный доступ к защищаемым данным или получить доступ на изменение, добавление или удаление защищаемых данных'
                    vulnerability_criticality: Вредоносная активность не обнаружена
                    discovered_at: '2021-01-22'
                    cvssv2: 5.8
                    cvssv3: 5.9
                    vector_v2: 'AV:N/AC:L/Au:M/C:P/I:P/A:P'
                    vector_v3: 'AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:L'
                    domain: oracle.com
                    host_ip: 95.101.178.195
                    port: 8080
                    host_name: 'https://www.oracle.com'
                    identification_src: 'https://www.oracle.com/security-alerts/cpuoct2023.html'
                    cve: 'https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2023-22071'
                    bdu_fstec: 'https://bdu.fstec.ru/vul/2023-06901'
                    references:
                      - source: NATIONAL VULNERABILITY DATABASE
                        url: 'https://nvd.nist.gov/vuln/detail/CVE-2023-22071'
                    software_vulnerabilities:
                      - cpe: Oracle Corp.
                        name: Database Server
                        path: /
                        version: от 19.3 до 19.19 включительно
                    dit_inc_result: Данные уточняются
                    removal_recommend: 'https://www.oracle.com/security-alerts/cpuoct2023.html'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-401.yaml
              examples: null
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-403.yaml
              examples: null
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-404.yaml
              examples: null
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-500.yaml
              examples: null
  /scanning-vulnerabilities:
    get:
      operationId: indexScanningVulnerability
      summary: indexScanningVulnerability
      tags:
        - scanning-vulnerabilities
      description: Получение списка уязвимостей найденными сканерами
      responses:
        '200':
          description: Список заявок
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: ../models/scanning-vulnerability.yaml
                  - $ref: ../models/components/pagination.yaml
                type: object
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-401.yaml
              examples: null
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-422.yaml
              examples: null
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/errors/error-500.yaml
              examples: null
      parameters:
        - schema:
            type: integer
            minimum: 1
            maximum: 100
            example: 10
          in: query
          name: page
          description: Номер страницы
        - schema:
            type: integer
            example: 10
          in: query
          name: per_page
          description: Кол-во элементов на странице
        - schema:
            type: string
            enum:
              - CLOSE
              - OPEN
            example: OPEN
          in: query
          name: status
          description: Статус
        - schema:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2}$'
            example: '2021-01-01'
            format: date
          in: query
          name: discovered_at_from
          description: Обнаружение - от
        - schema:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2}$'
            example: '2021-01-02'
            format: date
          in: query
          name: discovered_at_to
          description: Обнаружение - по
        - schema:
            type: string
          in: query
          name: search
          description: Поисковая строка
        - schema:
            type: string
            enum:
              - id
              - vulnerability_name
              - cvssv3
              - cve
              - discovered_at
              - status
            example: id
          in: query
          name: sort_field
          description: Колонка для сортировки
        - schema:
            type: string
            enum:
              - asc
              - desc
            example: asc
          in: query
          name: sort_order
          description: Направление сортировки
